services:
  opensearch01:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch01
    environment:
      - cluster.name=opensearch-cluster
      - cluster.initial_master_nodes=opensearch01
      - node.name=opensearch01
      - discovery.seed_hosts=opensearch02,opensearch03
      - bootstrap.memory_lock=true
      - node.roles=master,data,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_SECURITY_PLUGIN=true"
      - 'TZ=Asia/Seoul'
    ulimits:
      memlock:
          soft: -1
          hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  opensearch02:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch02
    environment:
      - cluster.name=opensearch-cluster
      - cluster.initial_master_nodes=opensearch01
      - node.name=opensearch02
      - discovery.seed_hosts=opensearch01,opensearch03
      - bootstrap.memory_lock=true
      - node.roles=master,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_SECURITY_PLUGIN=true"
      - 'TZ=Asia/Seoul'
    ulimits:
      memlock:
          soft: -1
          hard: -1
    ports:
      - "9201:9200"
      - "9301:9300"

  opensearch03:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch03
    environment:
      - cluster.name=opensearch-cluster
      - cluster.initial_master_nodes=opensearch01
      - node.name=opensearch03
      - discovery.seed_hosts=opensearch01,opensearch02
      - bootstrap.memory_lock=true
      - node.roles=master,data,ingest,ml
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_SECURITY_PLUGIN=true"
      - 'TZ=Asia/Seoul'
    ulimits:
      memlock:
          soft: -1
          hard: -1
    ports:
      - "9202:9200"
      - "9302:9300"

  dashboard:
    image: opensearchproject/opensearch-dashboards:2.17.1
    container_name: dashboard
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch01:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - 'TZ=Asia/Seoul'
    ports:
      - "5601:5601"
    depends_on:
      - opensearch01

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=miniodocker
      - MINIO_ROOT_PASSWORD=minio123
      - TZ=Asia/Seoul
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"